version: '3.7'

services:
  webserver:
    image: mariort/php-nginx:3.0
    volumes:
      - .:/www
    ports:
      - "80:80"
    environment: 
      - XDEBUG_CONFIG
    networks: 
      - default
    command: sh /www/docker/shell/webserver.sh

networks:
  default:
    name: symfony/umbra