version: '3.7'

services:
  webserver:
    image: mariort/php-nginx:3.0
    container_name: symfonyapi
    volumes:
      - .:/www
    ports:
      - "80:80"
    environment: 
      - XDEBUG_CONFIG
    networks: 
      - default
    command: sh /www/docker/shell/webserver.sh
      
  swaggerui:
    image: swaggerapi/swagger-ui:v3.22.1
    container_name: symfonyapi_docs
    volumes:
      - ./swagger/yaml:/code
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /code/openapi.yaml

networks:
  default:
    name: symfony/umbra