version: '3.7'

services:
  webserver:
    image: mariort/php-nginx:1.0
    container_name: ${WEBSERVER_CONTAINER_NAME}
    volumes:
      - .:/www
    ports:
      - "8080:80"
    networks: 
      - default
      
  swaggerui:
    image: swaggerapi/swagger-ui:v3.22.1
    container_name: ${WEBSERVER_CONTAINER_NAME}_docs
    volumes:
      - ./swagger/yaml:/code
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /code/${SWAGGER_FILENAME}

networks:
  default:
    name: ${DOCKER_DEFAULT_NETWORK}