version: '3.7'

services:
  docs:
    image: php:7.3-cli-alpine
    working_dir: /code
    volumes:
      - .:/code
    environment:
      SWAGGER_TARGET: /code/swagger/yaml/${SWAGGER_FILENAME}
      SWAGGER_PATH: /code/swagger/annotations /code/src
    command: sh /code/docker/shell/docs.sh

  composer:
    image: composer:1.6
    working_dir: /code
    volumes:
      - .:/code
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $SSH_AUTH_SOCK:/ssh-auth.sock
    environment:
      SSH_AUTH_SOCK: /ssh-auth.sock
    command: composer install -n --ignore-platform-reqs --no-scripts

  bootstrap:
    # network_mode: "none"
    image: busybox:1.29
    working_dir: /code
    volumes:
      - .:/code
    command: sh /code/docker/shell/bootstrap.sh
    
networks:
  default:
    name: ${DOCKER_DEFAULT_NETWORK}